# Generated by Django 6.0.2 on 2026-02-15 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100)),
                ('orden', models.IntegerField(unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Niveles educativos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institucion', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('INC', 'Incompleto'), ('COM', 'Completo'), ('TRU', 'Trunco'), ('CUR', 'Cursando')], max_length=3)),
                ('anio_inicio', models.IntegerField()),
                ('anio_fin', models.IntegerField(blank=True, null=True)),
                ('tiene_cedula', models.BooleanField(default=False)),
                ('numero_cedula', models.CharField(blank=True, max_length=20)),
                ('documento_verificado', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educacion', to='personas.persona')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='educacion.niveleducativo')),
            ],
            options={
                'verbose_name_plural': 'Educación',
                'ordering': ['-anio_fin', '-anio_inicio'],
            },
        ),
    ]
