# Generated by Django 6.0.2 on 2026-02-22 01:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion', '0001_initial'),
        ('personas', '0002_persona_acta_nacimiento_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='ciudad_institucion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad donde se localiza la institución'),
        ),
        migrations.AddField(
            model_name='educacion',
            name='tipo_documento_estudio',
            field=models.CharField(blank=True, choices=[('CER', 'Certificado'), ('TIT', 'Título'), ('CON', 'Constancia'), ('CAR', 'Carta de pasante'), ('OTR', 'Otro'), ('NIN', 'Ninguno')], max_length=3, verbose_name='Tipo de documento de estudio obtenido'),
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idioma', models.CharField(max_length=100, verbose_name='Idioma')),
                ('porcentaje_habla', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de dominio oral (habla)')),
                ('porcentaje_escribe', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de dominio escrito')),
                ('porcentaje_lee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de comprensión lectora')),
                ('plantel', models.CharField(blank=True, max_length=200, verbose_name='Plantel / institución donde lo estudió')),
                ('periodo_inicio', models.IntegerField(blank=True, null=True, verbose_name='Año de inicio del estudio')),
                ('periodo_fin', models.IntegerField(blank=True, null=True, verbose_name='Año de fin del estudio')),
                ('tiene_certificacion', models.BooleanField(default=False, verbose_name='Cuenta con certificación oficial')),
                ('tipo_certificacion', models.CharField(blank=True, max_length=100, verbose_name='Tipo de certificación (TOEFL, IELTS, DELF, etc.)')),
                ('nivel_certificacion', models.CharField(blank=True, max_length=100, verbose_name='Nivel que acredita la certificación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='personas.persona')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['idioma'],
            },
        ),
    ]
