# Generated by Django 6.0.2 on 2026-02-15 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioSocioeconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('VIS', 'Visita programada'), ('PRO', 'En proceso'), ('COM', 'Completado'), ('REV', 'En revisión'), ('APR', 'Aprobado'), ('REC', 'Rechazado'), ('CAN', 'Cancelado')], default='BOR', max_length=3)),
                ('fecha_programada_visita', models.DateTimeField(blank=True, null=True)),
                ('fecha_realizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('puntuacion_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='personas.persona')),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracion.tipoestudio')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Estudios socioeconómicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
