# Generated by Django 6.0.2 on 2026-02-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='comentarios_adicionales',
            field=models.TextField(blank=True, verbose_name='Comentarios adicionales del solicitante'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='expectativas_salariales',
            field=models.CharField(blank=True, max_length=200, verbose_name='Expectativas económicas para la vacante'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='medio_enterado_vacante',
            field=models.CharField(blank=True, choices=[('FAC', 'Facebook'), ('REF', 'Referencia'), ('OTR', 'Otro')], max_length=3, verbose_name='Medio por el que se enteró de la vacante'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='tiempo_traslado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiempo aproximado de traslado domicilio-empresa'),
        ),
    ]
