# Generated by Django 6.0.2 on 2026-02-22 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_empresacliente'),
        ('estudios', '0002_estudiosocioeconomico_comentarios_adicionales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='aspectos_negativos',
            field=models.TextField(blank=True, verbose_name='Aspectos negativos / áreas de oportunidad'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='aspectos_positivos',
            field=models.TextField(blank=True, verbose_name='Aspectos positivos'),
        ),
        migrations.AddField(
            model_name='estudiosocioeconomico',
            name='empresa_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios', to='configuracion.empresacliente', verbose_name='Empresa que solicita el estudio'),
        ),
        migrations.CreateModel(
            name='EstudioToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='estudios.estudiosocioeconomico')),
            ],
            options={
                'verbose_name': 'Token de estudio',
                'verbose_name_plural': 'Tokens de estudio',
            },
        ),
    ]
