# Generated by Django 6.0.2 on 2026-02-15 01:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonos_comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingresos_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('apoyo_familiar', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion_otros_ingresos', models.CharField(blank=True, max_length=200)),
                ('gasto_alimentacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_vivienda', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_educacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_salud', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto_deudas', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion_otros_gastos', models.CharField(blank=True, max_length=200)),
                ('tiene_automovil', models.BooleanField(default=False)),
                ('automovil_marca_modelo', models.CharField(blank=True, max_length=100)),
                ('automovil_anio', models.IntegerField(blank=True, null=True)),
                ('patrimonio_inmobiliario', models.CharField(choices=[('NINGUNA', 'Sin vivienda'), ('PROPIA', 'Vivienda propia'), ('INVERSION', 'Vivienda en inversión'), ('TERRENO', 'Terreno'), ('OTRO', 'Otro')], default='NINGUNA', max_length=20)),
                ('descripcion_patrimonio', models.TextField(blank=True)),
                ('tiene_creditos', models.BooleanField(default=False)),
                ('credito_hipotecario', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('credito_automotriz', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tarjetas_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('prestamos_personales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('otros_creditos', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion_otros_creditos', models.CharField(blank=True, max_length=200)),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='situacion_economica', to='estudios.estudiosocioeconomico')),
            ],
            options={
                'verbose_name_plural': 'Situaciones económicas',
            },
        ),
    ]
