# Generated by Django 6.0.2 on 2026-02-22 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacioneconomica',
            name='afore',
            field=models.CharField(blank=True, max_length=100, verbose_name='AFORE a la que está afiliado'),
        ),
        migrations.AddField(
            model_name='situacioneconomica',
            name='automovil_con_adeudo',
            field=models.BooleanField(default=False, verbose_name='El automóvil aún tiene pagos pendientes'),
        ),
        migrations.AddField(
            model_name='situacioneconomica',
            name='automovil_valor_comercial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor comercial del automóvil'),
        ),
        migrations.AddField(
            model_name='situacioneconomica',
            name='institucion_bancaria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Institución bancaria (tarjeta de débito)'),
        ),
        migrations.AddField(
            model_name='situacioneconomica',
            name='situacion_economica_percibida',
            field=models.CharField(blank=True, choices=[('MBU', 'Muy buena – Ingresos suficientes y ahorro regular'), ('BUE', 'Buena – Cubre necesidades básicas y ahorra ocasionalmente'), ('REG', 'Regular – Ingresos apenas cubren lo básico, sin ahorro'), ('MAL', 'Mala – Dificultades para cubrir necesidades básicas'), ('MMA', 'Muy mala – Depende de apoyo externo o tiene deudas sin cubrir')], max_length=3, verbose_name='Situación económica autopercibida'),
        ),
        migrations.AddField(
            model_name='situacioneconomica',
            name='tarjeta_credito_banco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banco(s) de tarjeta(s) de crédito'),
        ),
        migrations.AddField(
            model_name='situacioneconomica',
            name='tienda_departamental_adeudo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto aproximado de adeudo en tienda departamental'),
        ),
        migrations.AddField(
            model_name='situacioneconomica',
            name='tienda_departamental_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tienda(s) departamental(es) con crédito'),
        ),
    ]
