# Generated by Django 6.0.2 on 2026-02-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requiere_visita', models.BooleanField(default=True)),
                ('requiere_verificacion_laboral', models.BooleanField(default=True)),
                ('puntuacion_minima_aprobacion', models.IntegerField(default=70)),
            ],
            options={
                'verbose_name': 'Tipo de estudio',
                'verbose_name_plural': 'Tipos de estudio',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
