# Generated by Django 6.0.2 on 2026-03-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_empresacliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoestudio',
            name='secciones',
            field=models.JSONField(blank=True, default=list, help_text='Secciones incluidas en este tipo de estudio (candidato y evaluacion son obligatorias)', verbose_name='Secciones del estudio'),
        ),
    ]
