# Generated by Django 6.0.2 on 2026-02-25 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ANA', 'Analista'), ('INS', 'Inspector')], default='ANA', help_text='Determina las funciones a las que tiene acceso el usuario.', max_length=3, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, help_text='Desactiva para suspender el acceso sin borrar el usuario.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
    ]
