# Generated by Django 6.0.2 on 2026-02-15 01:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ACT', 'Actual'), ('ANT', 'Anterior'), ('REF', 'Referencia')], default='ACT', max_length=3)),
                ('calle', models.CharField(max_length=200)),
                ('numero_exterior', models.CharField(max_length=20)),
                ('numero_interior', models.CharField(blank=True, max_length=20)),
                ('entre_calles', models.CharField(blank=True, max_length=200)),
                ('colonia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('tipo_vivienda', models.CharField(choices=[('PRO', 'Propia'), ('PROHIP', 'Propia con hipoteca'), ('REN', 'Rentada'), ('PRE', 'Prestada'), ('FAM', 'Familiar'), ('OTR', 'Otro')], max_length=6)),
                ('material_construccion', models.CharField(blank=True, max_length=100)),
                ('numero_habitaciones', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_niveles', models.IntegerField(default=1)),
                ('tiene_agua', models.BooleanField(default=False)),
                ('tiene_luz', models.BooleanField(default=False)),
                ('tiene_drenaje', models.BooleanField(default=False)),
                ('tiene_gas', models.BooleanField(default=False)),
                ('tiene_internet', models.BooleanField(default=False)),
                ('tiene_tv_cable', models.BooleanField(default=False)),
                ('tiempo_residencia_anios', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_residencia_meses', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='personas.persona')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Domicilios',
            },
        ),
    ]
