# Generated by Django 6.0.2 on 2026-02-22 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='orden_limpieza',
            field=models.CharField(blank=True, choices=[('BUE', 'Bueno'), ('REG', 'Regular'), ('MAL', 'Malo')], max_length=3, verbose_name='Orden, mantenimiento y limpieza del inmueble'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='propietario_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del propietario / A nombre de quién está el domicilio'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='superficie_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Superficie aproximada (m²)'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_cochera',
            field=models.BooleanField(default=False, verbose_name='Cochera'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_cocina',
            field=models.BooleanField(default=False, verbose_name='Cocina'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_comedor',
            field=models.BooleanField(default=False, verbose_name='Comedor'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_enjarre',
            field=models.BooleanField(default=False, verbose_name='Enjarre en las paredes'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_loza',
            field=models.BooleanField(default=False, verbose_name='Loza'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_paredes_sin_enjarre',
            field=models.BooleanField(default=False, verbose_name='Paredes sin enjarre'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_patio_servicio',
            field=models.BooleanField(default=False, verbose_name='Patio de servicio'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_pavimentacion',
            field=models.BooleanField(default=False, verbose_name='Pavimentación'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_piso',
            field=models.BooleanField(default=False, verbose_name='Piso (mosaico/madera/porcelanato)'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_piso_cemento',
            field=models.BooleanField(default=False, verbose_name='Piso de cemento'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_puertas',
            field=models.BooleanField(default=False, verbose_name='Puertas'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_sala',
            field=models.BooleanField(default=False, verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_techo_lamina',
            field=models.BooleanField(default=False, verbose_name='Techo de lámina'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tiene_telefono_domicilio',
            field=models.BooleanField(default=False, verbose_name='Teléfono fijo en el domicilio'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tipo_inmueble',
            field=models.CharField(blank=True, choices=[('CAS', 'Casa'), ('DEP', 'Departamento')], max_length=3, verbose_name='Tipo de inmueble'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='valor_electrodomesticos',
            field=models.CharField(blank=True, choices=[('R1', '$1,000 - $10,000'), ('R2', '$10,000 - $20,000'), ('R3', '$20,000 - $50,000'), ('R4', 'Más de $50,000')], max_length=2, verbose_name='Valor aproximado de electrodomésticos'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='valor_inmueble',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor aproximado del inmueble'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='valor_muebles',
            field=models.CharField(blank=True, choices=[('R1', '$1,000 - $10,000'), ('R2', '$10,000 - $20,000'), ('R3', '$20,000 - $50,000'), ('R4', 'Más de $50,000')], max_length=2, verbose_name='Valor aproximado de muebles'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='numero_habitaciones',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tiempo_residencia_anios',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tiempo_residencia_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tiene_agua',
            field=models.BooleanField(default=False, verbose_name='Agua'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tiene_drenaje',
            field=models.BooleanField(default=False, verbose_name='Drenaje / Alcantarillado'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tiene_gas',
            field=models.BooleanField(default=False, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tiene_internet',
            field=models.BooleanField(default=False, verbose_name='Internet'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tiene_luz',
            field=models.BooleanField(default=False, verbose_name='Luz'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tiene_tv_cable',
            field=models.BooleanField(default=False, verbose_name='TV de paga / Cable'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('PRO', 'Propia'), ('PROHIP', 'Propia con hipoteca'), ('REN', 'Rentada'), ('PRE', 'Prestada'), ('FAM', 'Familiar'), ('OTR', 'Otro')], max_length=6),
        ),
    ]
