# Generated by Django 6.0.2 on 2026-02-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0002_domicilio_orden_limpieza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='observaciones_inmueble',
            field=models.TextField(blank=True, verbose_name='Observaciones del inmueble'),
        ),
    ]
