# Generated by Django 6.0.2 on 2026-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0003_domicilio_observaciones_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud GPS'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud GPS'),
        ),
    ]
