# Generated by Django 6.0.2 on 2026-02-15 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudios', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('IDE', 'Identificación oficial'), ('DOM', 'Comprobante de domicilio'), ('ING', 'Comprobante de ingresos'), ('EST', 'Estado de cuenta'), ('TIT', 'Título/Cédula'), ('ACT', 'Acta de nacimiento'), ('CUR', 'CURP'), ('RFC', 'RFC'), ('FOT', 'Fotografía'), ('OTR', 'Otro')], max_length=3)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tamaño', models.IntegerField(help_text='Tamaño en bytes')),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estudios.estudiosocioeconomico')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='personas.persona')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
