# Generated by Django 6.0.2 on 2026-02-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitadomiciliaria',
            name='comentarios_colonos',
            field=models.TextField(blank=True, verbose_name='Comentarios de vecinos / colonos'),
        ),
    ]
