# Generated by Django 6.0.2 on 2026-02-15 01:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('PER', 'Personal'), ('LAB', 'Laboral'), ('VEC', 'Vecinal'), ('FAM', 'Familiar'), ('COM', 'Comercial')], max_length=3)),
                ('nombre', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('parentesco_o_relacion', models.CharField(max_length=100)),
                ('tiempo_conocer_anios', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('domicilio', models.TextField(blank=True)),
                ('verificada', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_verificacion', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='personas.persona')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Referencias',
            },
        ),
    ]
