# Generated by Django 6.0.2 on 2026-02-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='actividad_tiempo_libre',
            field=models.TextField(blank=True, verbose_name='Actividades que realiza en su tiempo libre (según referencia)'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='conducta',
            field=models.TextField(blank=True, verbose_name='Conducta observada (según referencia)'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='cualidades',
            field=models.TextField(blank=True, verbose_name='Cualidades destacadas (según referencia)'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='lugares_laborado',
            field=models.TextField(blank=True, verbose_name='Lugares donde ha laborado (según referencia)'),
        ),
    ]
