# Generated by Django 6.0.2 on 2026-02-15 01:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_identificacion', models.CharField(choices=[('INE', 'INE/IFE'), ('PAS', 'Pasaporte'), ('CED', 'Cédula Profesional'), ('CAR', 'Cartilla Militar'), ('OTR', 'Otro')], max_length=3)),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('curp', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{18}$', 'CURP inválida')])),
                ('rfc', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^[A-Z&Ñ]{4}\\d{6}[A-Z0-9]{3}$', 'RFC inválido')])),
                ('email', models.EmailField(max_length=254)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15)),
                ('estado_civil', models.CharField(choices=[('SOL', 'Soltero/a'), ('CAS', 'Casado/a'), ('ULB', 'Unión Libre'), ('DIV', 'Divorciado/a'), ('VIU', 'Viudo/a'), ('SEP', 'Separado/a')], max_length=3)),
                ('numero_dependientes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'indexes': [models.Index(fields=['folio'], name='personas_pe_folio_a18f63_idx'), models.Index(fields=['curp'], name='personas_pe_curp_f060a6_idx'), models.Index(fields=['apellido_paterno', 'apellido_materno', 'nombre'], name='personas_pe_apellid_a312db_idx')],
            },
        ),
    ]
