# Generated by Django 6.0.2 on 2026-02-22 01:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='acta_nacimiento_numero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de acta de nacimiento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='actividades_tiempo_libre',
            field=models.TextField(blank=True, help_text='Tipo de actividad, frecuencia y tiempo dedicado', verbose_name='Actividades en tiempo libre'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cartilla_militar_folio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Folio de cartilla militar'),
        ),
        migrations.AddField(
            model_name='persona',
            name='estatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Estatura (cm)'),
        ),
        migrations.AddField(
            model_name='persona',
            name='facebook_perfil',
            field=models.CharField(blank=True, max_length=200, verbose_name='Perfil de Facebook'),
        ),
        migrations.AddField(
            model_name='persona',
            name='historial_residencias',
            field=models.TextField(blank=True, help_text='Lugar, período (año inicio-fin) y motivo del cambio de residencia', verbose_name='Historial de residencias anteriores'),
        ),
        migrations.AddField(
            model_name='persona',
            name='licencia_manejo_folio',
            field=models.CharField(blank=True, max_length=50, verbose_name='Folio de licencia de manejo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='nss',
            field=models.CharField(blank=True, max_length=11, verbose_name='NSS (Número de Seguridad Social)'),
        ),
        migrations.AddField(
            model_name='persona',
            name='periodos_sin_laborar',
            field=models.TextField(blank=True, help_text='Período (mes/año inicio-fin) y actividad durante ese tiempo', verbose_name='Períodos sin laborar'),
        ),
        migrations.AddField(
            model_name='persona',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(choices=[('SOL', 'Soltero/a'), ('CAS', 'Casado/a'), ('ULB', 'Unión Libre'), ('DIV', 'Divorciado/a'), ('VIU', 'Viudo/a'), ('SEP', 'Separado/a'), ('OTR', 'Otro')], max_length=3),
        ),
        migrations.CreateModel(
            name='SaludPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel_salud', models.CharField(blank=True, choices=[('EXC', 'Excelente'), ('BUE', 'Buena'), ('REG', 'Regular'), ('MAL', 'Mala')], max_length=3, verbose_name='Estado de salud general')),
                ('enfermedades_cronicas', models.TextField(blank=True, help_text='Especificar enfermedad y tratamiento que lleva', verbose_name='Enfermedades crónicas / condiciones médicas / alergias / discapacidad')),
                ('antecedentes_familiares', models.TextField(blank=True, help_text='Enfermedades y familiar(es) que las han padecido', verbose_name='Antecedentes de enfermedades familiares')),
                ('consumo_sustancias', models.TextField(blank=True, help_text='Bebidas alcohólicas, tabaco, medicamentos sin prescripción, estupefacientes u otros; indicar frecuencia', verbose_name='Consumo de sustancias')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salud', to='personas.persona')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salud de persona',
                'verbose_name_plural': 'Salud de personas',
            },
        ),
    ]
