# Generated by Django 6.0.2 on 2026-03-28 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_acta_nacimiento_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='curp',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator('^$|^[A-Z0-9]{18}$', 'CURP inválida (debe tener 18 caracteres alfanuméricos en mayúsculas)')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOL', 'Soltero/a'), ('CAS', 'Casado/a'), ('ULB', 'Unión Libre'), ('DIV', 'Divorciado/a'), ('VIU', 'Viudo/a'), ('SEP', 'Separado/a'), ('OTR', 'Otro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('INE', 'INE/IFE'), ('PAS', 'Pasaporte'), ('CED', 'Cédula Profesional'), ('CAR', 'Cartilla Militar'), ('OTR', 'Otro')], max_length=3),
        ),
    ]
