# Generated by Django 6.0.2 on 2026-02-15 01:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_completo', models.CharField(max_length=300)),
                ('parentesco', models.CharField(max_length=100)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('tipo_dependencia', models.CharField(choices=[('TOT', 'Total'), ('PAR', 'Parcial'), ('IND', 'Independiente'), ('ECO', 'Aporta económicamente')], max_length=3)),
                ('ocupacion', models.CharField(blank=True, max_length=200)),
                ('escolaridad', models.CharField(blank=True, max_length=100)),
                ('vive_en_domicilio', models.BooleanField(default=True)),
                ('aporta_ingreso', models.BooleanField(default=False)),
                ('monto_aportacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_familiar', to='personas.persona')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Grupos familiares',
            },
        ),
    ]
