# Generated by Django 6.0.2 on 2026-02-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupofamiliar',
            name='ciudad_residencia',
            field=models.CharField(blank=True, help_text='Completar si el familiar no vive en el domicilio del solicitante', max_length=100, verbose_name='Ciudad de residencia'),
        ),
        migrations.AddField(
            model_name='grupofamiliar',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono del familiar'),
        ),
    ]
