# Generated by Django 6.0.2 on 2026-02-15 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=200)),
                ('telefono_empresa', models.CharField(max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('es_trabajo_actual', models.BooleanField(default=False)),
                ('salario_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_jefe', models.CharField(max_length=200)),
                ('telefono_jefe', models.CharField(max_length=15)),
                ('motivo_separacion', models.TextField(blank=True)),
                ('verificada', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_laboral', to='personas.persona')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historiales laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
